<?php

namespace App\Providers;

use App\Services\AdminServiceImpl;
use App\Services\Impl\AdminService;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class AdminServiceProvider extends ServiceProvider implements DeferrableProvider
{
    public array $singletons = [
        AdminService::class => AdminServiceImpl::class,
    ];

    public function provides()
    {
        return [AdminService::class];
        // TODO: Change the autogenerated stub
    }


    public function register(): void
    {
        //
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}
